name: madar_app
description: "TV Box Application to manage Ads and content remotely."
publish_to: "none"

version: 1.0.9

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^11.1.1
  package_info_plus: ^8.0.2
  android_id: ^0.3.6
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.8
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   # ← add this

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/14.png"  # ← your logo
  adaptive_icon_background: "#0B1220"  # (Android 8+ background color, tweak if you want)
  adaptive_icon_foreground: "assets/logo/14.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/logo/1.png
    - assets/logo/2.png
    - assets/logo/3.png
    - assets/logo/4.png
    - assets/logo/5.png
    - assets/logo/6.png
    - assets/logo/7.png
    - assets/logo/9.png
    - assets/logo/10.png
    - assets/logo/11.png
    - assets/logo/12.png
    - assets/logo/13.png
    - assets/logo/14.png

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans.ttf
